### ISSUE TITLE
DPL-524 Establish process maps for TOL/SciOps Sample ingestion

### ISSUE THREAD

**Issue by emrojo** [sanger/tol-lab-share#12]
**Description**
Establish a shared understanding of the process of sample ingestion between TOL - SciOps - process maps agreed with ToL and SciOps by Oct. 

Discoverable process which can be viewed by all stakeholders as an agreed standard of how to request work

**Who the primary contacts are for this work**
Eduardo
Steve

**Knowledge or Stake holders**
TOL, SciOps

**Additional context or information**

Enabling Platforms & Core labs (Progs: ToL), SciOps - Long read, Sample Management, SSRs

**Comment by emrojo** [comment]
Diagrams at: https://lucid.app/lucidchart/33b22c5e-cd4a-4cd9-8c7c-2ae1f110b347/edit?invitationId=inv_daeccc47-5803-4309-bd63-1a9e8fc4bf6b&page=0_0#

**Comment by emrojo** [comment]
Stories created for next iteration that will allow CREATE:

*  https://github.com/sanger/tol-lab-share/issues/15
*  https://github.com/sanger/tol-lab-share/issues/16

**Comment by stevieing** [comment]
@emrojo DPL-540 is not on your diagram. I also thought there was another more detailied diagram which you showed me? 
We also need to think about ingestion into Samples extraction.
A couple of other things to think about. We will need some kind of interaction with stakeholders e.g. working with ToL and SSRs to show this working so I think it needs an extra story at least maybe 2 to ensure that we cover everything.
Iy might be worth engaging with ToL sooner rather than later and seeing what they are planning to do.

**Comment by emrojo** [comment]
Hi, 

Stories at the moment is this group:

https://github.com/sanger/tol-lab-share/issues?q=is%3Aissue+is%3Aopen+label%3A%22ToL+Sample+ingestion+%28phase+2%29%22

**Comment by stevieing** [comment]
Closed as done.
